[{"name": "test.test_binding_sites.BindingSites.test_euclidean1", "status": "failed", "message": "0.9895 != 0.9865 within 4 places (0.0030000000000000027 difference) : Function cluster_euclidean returned incorrect accuracy for file src/data.seq!", "passed": false, "points": ["p06-07.2"], "backtrace": ["  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e07_binding_sites/test/test_binding_sites.py\", line 52, in test_euclidean1\n    self.assertAlmostEqual(acc, 0.9865, places=4,\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 966, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_binding_sites.BindingSites.test_euclidean2", "status": "passed", "message": "", "passed": true, "points": ["p06-07.2"], "backtrace": []}, {"name": "test.test_binding_sites.BindingSites.test_euclidean3", "status": "passed", "message": "", "passed": true, "points": ["p06-07.2"], "backtrace": []}, {"name": "test.test_binding_sites.BindingSites.test_euclidean4", "status": "failed", "message": "'metric' not found in {'n_clusters': 2, 'affinity': 'euclidean', 'linkage': 'average'} : You did not give the 'metric' parameter to AgglomerativeClustering!", "passed": false, "points": ["p06-07.2"], "backtrace": ["  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e07_binding_sites/test/test_binding_sites.py\", line 82, in test_euclidean4\n    self.assertIn('metric', kwargs, msg=\"You did not give the 'metric' parameter to AgglomerativeClustering!\")\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 1179, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 753, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_binding_sites.BindingSites.test_features_and_labels", "status": "errored", "message": "'DataFrame' object has no attribute 'flat'", "passed": false, "points": ["p06-07.1"], "backtrace": ["  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e07_binding_sites/test/test_binding_sites.py\", line 42, in test_features_and_labels\n    d = Counter(A.flat)\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/site-packages/pandas/core/generic.py\", line 5465, in __getattr__\n    return object.__getattribute__(self, name)\n"]}, {"name": "test.test_binding_sites.BindingSites.test_hamming1", "status": "failed", "message": "0.9985 != 0.9975 within 4 places (0.0010000000000000009 difference) : Function cluster_hamming returned incorrect accuracy for file src/data.seq!", "passed": false, "points": ["p06-07.3"], "backtrace": ["  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e07_binding_sites/test/test_binding_sites.py\", line 90, in test_hamming1\n    self.assertAlmostEqual(acc, 0.9975, places=4, msg=\"Function cluster_hamming returned incorrect accuracy for file %s!\" % \"src/data.seq\")\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 966, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_binding_sites.BindingSites.test_hamming2", "status": "passed", "message": "", "passed": true, "points": ["p06-07.3"], "backtrace": []}, {"name": "test.test_binding_sites.BindingSites.test_hamming3", "status": "passed", "message": "", "passed": true, "points": ["p06-07.3"], "backtrace": []}, {"name": "test.test_binding_sites.BindingSites.test_hamming4", "status": "failed", "message": "'metric' not found in {'n_clusters': 2, 'affinity': 'precomputed', 'linkage': 'average'} : You did not give the 'metric' parameter to AgglomerativeClustering!", "passed": false, "points": ["p06-07.3"], "backtrace": ["  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/phyu/mooc/dap/mooc-data-analysis-with-python-2024-2025/part06-e07_binding_sites/test/test_binding_sites.py\", line 126, in test_hamming4\n    self.assertIn('metric', kwargs, msg=\"You did not give the 'metric' parameter to AgglomerativeClustering!\")\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 1179, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/home/phyu/anaconda3/envs/myenv/lib/python3.8/unittest/case.py\", line 753, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_binding_sites.BindingSites.test_toint", "status": "passed", "message": "", "passed": true, "points": ["p06-07.1"], "backtrace": []}]